### ISSUE TITLE
Cannot connect to director when setting bosh target

### ISSUE THREAD

**Issue by Djasoni** [cloudfoundry/bosh-lite#287]
hi,

Now I want to set up bosh to deploy CouldFoundary, so I follow the steps of "Deploying Locally with BOSH Lite" and then I got a mistake like bellow:

 [root@oc4346816072 ~]# bosh target 192.168.50.4 lite
[WARNING] cannot access director, trying 4 more times...
[WARNING] cannot access director, trying 3 more times...
[WARNING] cannot access director, trying 2 more times...
[WARNING] cannot access director, trying 1 more times...
cannot access director (execution expired)

when I set the bosh target I got the error.(using virtualbox as vagrant provider).

who can help me?

thanks a lot

**Comment by Djasoni** [comment]
after run "route add -net 10.244.0.0/19 gw 192.168.50.4"
it works fun

**Comment by uvwild** [comment]
clarifying on which host you set routes to where would really make it much easier to understand this.

**Comment by codyaray** [comment]
For anyone who comes across this (but isn't using docker)... for me it turned out to be an old openssl version (mac system installed), and once I updated openssl (`brew install openssl; brew link openssl -force`) I still had to recompile ruby against that version (`rbenv install 2.0.0p647; rbenv global 2.0.0p647`). Fun stuff.
