### ISSUE TITLE
failed to vagrant up an aws instance with error Value () for parameter groupId is invalid.

### ISSUE THREAD

**Issue by kiwiwin** [cloudfoundry/bosh-lite#312]
any idea on how to solve this problem?

i try to launch instance using non-vpc mode. find document in 

https://github.com/mitchellh/vagrant-aws

security_groups - An array of security groups for the instance. If this instance will be launched in VPC, this must be a list of security group Name. For a nondefault VPC, you must use security group IDs instead (http://docs.aws.amazon.com/cli/latest/reference/ec2/run-instances.html).

so i set security id env variable like 

export BOSH_LITE_SECURITY_GROUP=sg-abcd1234

but get the same error message saying that 

InvalidParameterValue => Value () for parameter groupId is invalid. The value cannot be empty

**Comment by kiwiwin** [comment]
solved by checking security group id that not working with target vpc

**Comment by StanleyShen** [comment]
I met the same problem when I am running vagrant up --provider=aws
I have set environment for below:
BOSH_AWS_ACCESS_KEY_ID="affsfdfdfd"
BOSH_AWS_SECRET_ACCESS_KEY="sfsfdsdfsdfsfs"
BOSH_LITE_SECURITY_GROUP="sg-c63sdfsfsfsfs"

could you please tell more about "solved by checking security group id that not working with target vpc" ?

**Comment by cordoval** [comment]
@StanleyShen i think he realized that aws_vpc needs to specify a  azs = "${var.availability_zone}"

it is a comma separated list of availability zones, when you are starting with terraform this is often a common pitfall. The caveat is to ensure that you set the AZ the same as the VPC AZ or at least within the set. Otherwise terraform api calls to the aws api will filter the id that you are passing and will ultimately end up being null ``()``` and obviously it is going to fail and will totally confuse you, like it did to me at first :blush:

**Comment by cordoval** [comment]
actually also check the instance ami you are trying to run is for the region AZ you are trying to deploy

**Comment by andrepapaz** [comment]
Check if your region is ok with your ami and key pair.
