### ISSUE TITLE
Can deploy it in windows or not?

### ISSUE THREAD

**Issue by warmchang** [cloudfoundry/bosh-lite#366]
Hi, 

I found that cf-cli support the widonws platform (https://github.com/cloudfoundry/cli). So I'd like to know bosh-lite can be deployed in windows host OS with virtualbox or not?

Thanks.

**Comment by dpb587-pivotal** [comment]
Hi - you can run bosh-lite on Windows since it is managed by vagrant, but once booted you'll also need the `bosh_cli` which isn't officially supported or tested on Windows. I've seen a few blog posts on the web about people having varying success if you want to search for some ideas and see if they're feasible for you.

**Comment by sykesm** [comment]
The bosh-lite vagrant box contains the bosh cli. While a bit kludgey, you can `vagrant ssh` into the bosh-lite vm and work with bosh releases in there. Since you're on windows, vagrant synced folders may cause you some trouble with permissions and such so you would probably keep everything in the vagrant VMs file system.

Basically, you can make it work but it probably won't be the optimal work flow.

**Comment by warmchang** [comment]
@dpb587-pivotal @sykesm , thank you! I will try it in local environment.
