### ISSUE TITLE
Revoking roles is not restricting users.

### ISSUE THREAD

**Issue by phanikumar1210** [cloudfoundry/bosh-lite#382]
I have revoked the space-developer role for the admin user but I was still able to upload an application. I have followed the following link https://docs.cloudfoundry.org/concepts/roles.html#roles and revoked rights for admin user using the command 
**cf unset-space-role admin sampleorg development SpaceDeveloper**

But revoking the same for other users is working fine. Could anyone help me on this or can't we restrict admin users from pushing the application. Any suggestion or information is appreciated.

**Comment by dpb587-pivotal** [comment]
Admin may have special privileges regardless of roles.

You should open this issue in the [cf-release](https://github.com/cloudfoundry/cf-release) because it's specific to the CloudFoundry release (bosh-lite just happens to be the server where it's running). Alternatively, you might want to ask in the [cloudfoundry.slack.com](slack.cloudfoundry.org) channels.
