### ISSUE TITLE
Blobstore error: Failed to fetch object, underlying error: #<HTTPClient::ReceiveTimeoutError: execution expired> 

### ISSUE THREAD

**Issue by ivandavidov** [cloudfoundry/bosh-lite#428]
I've been following the official instructions about [deploying Cloud Foundry](http://docs.cloudfoundry.org/deploying/common/deploy.html) on my local bosh-lite VM. I am currently stuck with HTTP timeout while bosh was trying to fetch ``dotnet-core-buildpack`` from the blobstore:

```
Building dotnet-core-buildpack...
  Using final version '1e561dd9d5e980c690759e37a711b0f03488608d'
  Downloading from blobstore (id=78751dff-018f-4339-b702-1437c5a5b921)...
Blobstore error: Failed to fetch object, underlying error: #<HTTPClient::ReceiveTimeoutError: execution expired>
```

You can find the full output, including the ruby/gem stacktrace [here](https://gist.github.com/ivandavidov/da4430cf3d9bf37c87d946e429b897a3).

I suspect this error is due to the weak CPU on my local machine (N3700 CPU, 8GB RAM, Ubuntu 16.04 LTS). This is in line with the other issues of similar type which I opened recently.

**My question:** is there a way to explicitly set/increase the timeout which is causing me troubles?

Regards,
Ivan Davidov

**Comment by ivandavidov** [comment]
**Yet another question:** I assume the ``dotnet-core-buildpack`` is too big and my CPU is too weak which causes the issue. Apart from increasing the timeout, is it possible to exclude this buildpack from the release? That said, should I look in the YAML manifest file in the relase (cf-258) or I should try to remove this pack from somewhere else?

Thank you!

**Comment by ivandavidov** [comment]
Even though I managed to workaround my issue by using nothing but a terminal window on my Ubuntu OS (no browser, no other running apps), the issue is still there - the default timeouts may work fine in cloud environment but they are causing troubles on not-so-great entry level laptops like mine.

**Comment by dpb587-pivotal** [comment]
While Cloud Foundry does utilize a fair bit of CPU and memory, this seems more like an internet connectivity issue and retrying the download may fix it. I don't think a weak CPU should have much to do with this error since HTTP downloads are cheap.

I do recommend trying CF on a cloud somewhere if you're not having luck with your local machine - it may save you some time and hassle in the long-run. Feel free to follow up if you encounter other errors, or join the #bosh channel in https://slack.cloudfoundry.org.
